version: '1.0'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_URL=http://localhost:3001
    depends_on:
      - backend
  db:
    image: postgres:alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dutiesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
